### ISSUE TITLE
Display in front end

### ISSUE THREAD

**Issue by claraloustau** [bnomei/kirby3-pageviewcounter#4]
Hello, 
Thanks for your plugin ! Is there a way to display the counter in the front end ?
Thanks

**Comment by bnomei** [comment]
hi. you can use the static method and forward the id of the page
https://github.com/bnomei/kirby3-pageviewcounter/blob/c0f21cbf21a7084d75cc257b5e603363364f6bcb/classes/PageViewCounter.php#L65

**in you template like default.php**
```php
<?php

echo \Bnomei\PageViewCounter::singleton()->count($page->id());
```

**Comment by bnomei** [comment]
fixed should have been `\Bnomei\PageViewCounter::singleton()->count($id)`

**Comment by claraloustau** [comment]
Thank you @bnomei !

**Comment by claraloustau** [comment]
Is there a way to make a sortBy() on the count($id) for a blog ?
Something like : 
`$mostclicks = $page->children->sortBy(\Bnomei\PageViewCounter::singleton()->count($id), 'desc');
`

**Comment by claraloustau** [comment]
Hello bnomei, is there a way to convert 1000 to 1k ? thank you

**Comment by bnomei** [comment]
try `$formatedSize = I18n::formatNumber($count);`
