### ISSUE TITLE
[K4] Cannot access offset of type string on string

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-pageviewcounter#6]
I'm not sure this issue related with K4.

![screen-capture-1746-Kirby CMS Debugger-plugins test](https://github.com/bnomei/kirby3-pageviewcounter/assets/3393422/29ecec1b-5482-4306-9ea4-e966434044a6)

Plugin 1.5.0
Kirby 4.0.0-rc.2
PHP 8.1.23
Windows 10
XAMPP

**Comment by bnomei** [comment]
i can not replicate but i upgraded dependencies and did a test on k4 myself without having issues (osx, php8.2, herd)

**Comment by afbora** [comment]
Still same. Could you access to pixel image address, please? `plugins.test/plugins/pageviewcounter/counter-pixel`

I'm getting console error:

> GET http://plugins.test/plugins/pageviewcounter/counter-pixel 500 (Internal Server Error)

**Comment by bnomei** [comment]
maybe your local server can not create the png on the fly using the php libs? try echo ing out an empty string and exit instead.

https://github.com/bnomei/kirby3-pageviewcounter/blob/d7dfcbcb81d7f12582a619b674fe20bfeaa12311/classes/PageViewCounter.php#L77

**Comment by bnomei** [comment]
i added a try/catch with dumping the exception message in most recent release. maybe that helps to spot the issue at hand

**Comment by bnomei** [comment]
@afbora did the recent changes help you to get a better debug message?

**Comment by afbora** [comment]
@bnomei Sorry for the delay. Pixel error is gone but always page view count is 0 and page last visited is 1970-01-01 02:0:0. I tested with both `counterImage` and `counterCss` but no luck. Also SQLite database is always empty.

**Comment by afbora** [comment]
Maybe this is about my local setup or windows?

**Comment by bnomei** [comment]
i have both versions before and after recent fix running on servers in production without issues. since servers are rarly windows based i dont really want to spend time to debug this.

**Comment by nilshoerrmann** [comment]
Just for your information: I've just got the same error using MAMP.
